paths:
  /api/dev/products:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              status:
                type: string
                description: The status of the response
                example: "success"
              
              payload:
                type: object
                properties:
                  docs:
                    type: array
                    items:
                      type: object
                      properties:
                        owner:
                          type: string
                          example: admin
                        _id:
                          type: string
                          example: 6558dd604e0a87e8653355f1
                        title:
                          type: string
                          example: MacBook Pro 2023
                        code:
                          type: string
                          example: '3'
                        category:
                          type: string
                          example: Laptop
                        description:
                          type: string
                          example: The MacBook Pro 2023 is Apple's flagship laptop, featuring a stunning Retina display, M2 Pro chip, an improved Magic Keyboard, and outstanding performance for creative professionals.
                        stock:
                          type: integer
                          example: 37
                        price:
                          type: integer
                          example: 2199
                        status:
                          type: boolean
                          example: true
                        thumbnails:
                          type: array
                          items:
                            type: string
                        createdAt:
                          type: string
                          format: date-time
                          example: '2023-11-18T15:50:56.395Z'
                        updatedAt:
                          type: string
                          format: date-time
                          example: '2024-01-25T15:18:43.185Z'
                        __v:
                          type: integer
                          example: 0
                  
                  totalDocs:
                    type: integer
                    example: 10
                  limit:
                    type: integer
                    example: 10
                  totalPages:
                    type: integer
                    example: 1
                  page:
                    type: integer
                    example: 1
                  pagingCounter:
                    type: integer
                    example: 1
                  hasPrevPage:
                    type: boolean
                    example: false
                  hasNextPage:
                    type: boolean
                    example: false
        500: 
          description: Internal Server Error
    post:
      summary: Create a new product
      tags:
        - Products
      
      security:
        - auth:
            - 'admin'
            - 'premium'
      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: The title of the product
                  example: "Product Name"
                code:
                  type: string
                  description: The unique code of the product
                  example: "PROD001"
                owner:
                  type: string
                  description: The owner of the product
                  example: "admin"
                category:
                  type: string
                  description: The category of the product
                  example: "Electronics"
                description:
                  type: string
                  description: The description of the product
                  example: "This is a great product."
                stock:
                  type: integer
                  description: The stock quantity of the product
                  example: 100
                price:
                  type: number
                  description: The price of the product
                  example: 99.99
                status:
                  type: boolean
                  description: The status of the product (true for active, false for inactive)
                  example: true
                thumbnails:
                  type: array
                  description: Array of image URLs for product thumbnails
                  items:
                    type: string
      responses:
        200:
          description: Product created successfully
        
        400:
          description: Bad request, invalid input, or missing required fields
        
        500:
          description: Internal server error
  
  /api/dev/products/{id}:
    get:
      summary: Get a product by ID
      tags:
        - Products
      
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the product to retrieve
          example: "60a8e2d97ae4b7a59c8d2b4e"
      responses:
        200:
          description: OK

        500:
          description: Internal server error
    
    put:
      summary: Update product by ID
      tags:
        - Products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the product to retrieve
          example: "60a8e2d97ae4b7a59c8d2b4e"
      responses:
        200:
          description: OK

        500:
          description: Internal server error
    
    delete:
      summary: Delete product by ID
      tags:
        - Products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the product to retrieve
          example: "60a8e2d97ae4b7a59c8d2b4e"
      responses:
        200:
          description: OK

        500:
          description: Internal server error

components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
          description: The title of the product
          example: "Product Name"
        code:
          type: string
          description: The unique code of the product
          example: "PROD001"
        owner:
          type: string
          description: The owner of the product
          example: "admin"
        category:
          type: string
          description: The category of the product
          example: "Electronics"
        description:
          type: string
          description: The description of the product
          example: "This is a great product."
        stock:
          type: integer
          description: The stock quantity of the product
          example: 100
        price:
          type: number
          description: The price of the product
          example: 99.99
        status:
          type: boolean
          description: The status of the product (true for active, false for inactive)
          example: true
        thumbnails:
          type: array
          description: Array of image URLs for product thumbnails
          items:
            type: string
      required:
        - title
        - code
        - category
        - description
        - stock
        - price